packages:
  - server
  - client
  - shared
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  canvas: true
  core-js: true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: set this to true or false
  sharp: true

overrides:
  vite: "^8.0.0"
