/**
 * wipe-g7-batch-sectioning.ts
 *
 * Removes the seeded SY 2026-2027 batch-sectioning test data generated by
 * seed-g7-incoming-batch-sectioning.ts.
 *
 * Targets:
 *   - EnrollmentApplication rows with trackingNumber starting with G7BS-
 *   - Related EarlyRegistrationApplication rows created for SCP learners
 *   - Child records linked to those applications
 *   - Learners that have no remaining applications after the wipe
 *
 * Usage:
 *   pnpm --filter server run db:wipe-g7-batch-sectioning
 */

import "dotenv/config";
import { PrismaClient } from "../../../src/generated/prisma/index.js";
import { PrismaPg } from "@prisma/adapter-pg";
import * as pg from "pg";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Wiping Grade 7 batch-sectioning seed data for SY 2026-2027...");

  const targetYear = await prisma.schoolYear.findUnique({
    where: { yearLabel: "2026-2027" },
  });

  if (!targetYear) {
    console.log("Target school year not found. Nothing to wipe.");
    return;
  }

  const seededApps = await prisma.enrollmentApplication.findMany({
    where: {
      schoolYearId: targetYear.id,
      trackingNumber: { startsWith: "G7BS-" },
    },
    select: {
      id: true,
      status: true,
      learnerId: true,
      earlyRegistrationId: true,
    },
  });

  if (seededApps.length === 0) {
    console.log("No G7 batch-sectioning seed rows found.");
    return;
  }

  const appIds = seededApps.map((row) => row.id);
  const readyForSectioningAppIds = seededApps
    .filter((row) => row.status === "READY_FOR_SECTIONING")
    .map((row) => row.id);
  const earlyRegIds = seededApps
    .map((row) => row.earlyRegistrationId)
    .filter((id): id is number => id !== null);
  const candidateLearnerIds = Array.from(
    new Set(seededApps.map((row) => row.learnerId).filter((id): id is number => id !== null)),
  );

  const remainingEnrollmentLearners = await prisma.enrollmentApplication.findMany({
    where: {
      learnerId: { in: candidateLearnerIds },
      id: { notIn: appIds },
    },
    select: { learnerId: true },
  });

  const remainingEarlyRegLearners = await prisma.earlyRegistrationApplication.findMany({
    where: {
      learnerId: { in: candidateLearnerIds },
      id: { notIn: earlyRegIds },
    },
    select: { learnerId: true },
  });

  const keepLearnerIds = new Set([
    ...remainingEnrollmentLearners.map((row) => row.learnerId).filter((id): id is number => id !== null),
    ...remainingEarlyRegLearners.map((row) => row.learnerId).filter((id): id is number => id !== null),
  ]);

  const learnerIdsToDelete = candidateLearnerIds.filter((id) => !keepLearnerIds.has(id));

  await prisma.$transaction(async (tx) => {
    if (readyForSectioningAppIds.length > 0) {
      await tx.enrollmentApplication.updateMany({
        where: { id: { in: readyForSectioningAppIds } },
        data: {
          status: "PENDING_CONFIRMATION",
          confirmationConsent: false,
        },
      });
    }

    await tx.enrollmentRecord.deleteMany({
      where: { enrollmentApplicationId: { in: appIds } },
    });

    await tx.applicationFamilyMember.deleteMany({
      where: { enrollmentId: { in: appIds } },
    });

    await tx.applicationChecklist.deleteMany({
      where: { enrollmentId: { in: appIds } },
    });

    await tx.enrollmentPreviousSchool.deleteMany({
      where: { applicationId: { in: appIds } },
    });

    await tx.enrollmentProgramDetail.deleteMany({
      where: { applicationId: { in: appIds } },
    });

    await tx.applicationAddress.deleteMany({
      where: { enrollmentId: { in: appIds } },
    });

    await tx.earlyRegistrationAssessment.deleteMany({
      where: { applicationId: { in: earlyRegIds } },
    });

    await tx.enrollmentApplication.deleteMany({
      where: { id: { in: appIds } },
    });

    await tx.earlyRegistrationApplication.deleteMany({
      where: { id: { in: earlyRegIds } },
    });

    let deletedLearners = 0;
    if (learnerIdsToDelete.length > 0) {
      const result = await tx.learner.deleteMany({
        where: { id: { in: learnerIdsToDelete } },
      });
      deletedLearners = result.count;
    }

    console.log(`Deleted ${appIds.length} enrollment application(s).`);
    console.log(`Deleted ${earlyRegIds.length} early registration application(s).`);
    console.log(`Deleted ${deletedLearners} learner record(s) with no remaining applications.`);
    console.log(`Kept ${keepLearnerIds.size} learner record(s) that have other applications.`);
  });

  console.log("Wipe complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });